### ISSUE TITLE
Suggestion: Allow moving of UI

### ISSUE THREAD

**Issue by AgentX2006** [zeeshanabid94/ZoningToolkitCS2#1]
As is the UI covers most of the dropdown that allows access to Mods. Being able to move it would be nice.

Also thanks for this mod. Not being able to control zoning has been the one thing that kept making me want to stop playing CS:2.

**Comment by zeeshanabid94** [comment]
Thanks for the suggestion. I am moving the zoning UI to the right by default so that is out of the way of the Mods access dropdown.

Will add a feature for moving the UI later.
